# taplo: schema="https://json.schemastore.org/rustfmt.json"

fn_args_layout = "Tall"
group_imports = "StdExternalCrate"
merge_imports = true

# Basic
hard_tabs = true
max_width = 160
style_edition = "2024"
tab_spaces = 2

# Imports
imports_granularity = "One"
reorder_imports = true

# Format comments
comment_width = 160
wrap_comments = true

# Misc
format_code_in_doc_comments = true
inline_attribute_width = 0
match_arm_blocks = false
match_block_trailing_comma = true
newline_style = "Unix"
reorder_impl_items = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
